name: CICD Pipeline

on:
 push:
   branches: ["main"]

jobs:
 build-and-push:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4  
      
    - name: initialize Repo
      run: | 
        echo "Starting CI build process on Ubuntu!" 
        uname -a
    
    - name: Check the docker installtion 
      run: |
       docker 
       docker images

    - name: Run Docker Container
      run : |
       docker run hello-world
