name: CICD Pipeline

on:
 push:
   branches: ["main"]

jobs:
 build-and-push:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4  
      
    - name: print welcome message
      run: echo "Starting CI build process on Ubuntu!"
    
    - name: run test suite
      run: |
       echo "Running unit tests..." 
       echo ""All tests passed successfully!
     
